### PR TITLE
Add iMessage/SMS Mouseless Messenger

### PR DESCRIPTION
**Pull request by stephancasas**
This workflow enables users to read and send iMessage or SMS messages from Alfred. Preview conversations by pressing *Shift*.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you for the submission. Can you explain the reasoning behind some of the choices?

* [Using `curl` on a file](https://github.com/stephancasas/alfred-mouseless-messenger/blob/ba2334b7a44217b03a9d283f91eb636a38ac7b73/src/conversations.jxa.js#L150L151), with `--location` and `--request GET`. Neither of those should have an effect on a file, and using `curl` for it is atypical. Are you just reading the file’s contents? Why not `cat`?
* Having an `alfred_workflow_installed` Workflow Environment Variable.
* Encoding images as base64 and writing them, instead of including them by as files.

**Comment by stephancasas** [comment]
> Thank you for the submission. Can you explain the reasoning behind some of the choices?
> 

> * [Using `curl` on a file](https://github.com/stephancasas/alfred-mouseless-messenger/blob/ba2334b7a44217b03a9d283f91eb636a38ac7b73/src/conversations.jxa.js#L150L151), with `--location` and `--request GET`. Neither of those should have an effect on a file, and using `curl` for it is atypical. Are you just reading the file’s contents? Why not `cat`?

I dropped this in from another project where I was pulling the file's path from the focused Finder selection. The JXA exposures for Finder can yield colon-delimited path names, or `file://` URLs, but not native POSIX paths. This is at least insofar as my own JXA knowledge runs. I'm sure someone's done it, but I was trying to keep things slim. `cat` would probably work here no problem.

> * Having an `alfred_workflow_installed` Workflow Environment Variable.

This is used to install the images once, which are base64-encoded.

> * Encoding images as base64 and writing them, instead of including them by as files.

If there's a better way to include these, I'm definitely open to the suggestion. I'm not deeply familiar with all of the idiosyncrasies of packaging Alfred workflows, so I included them the way I'd bundle them as a web dev delivering a single-file JS component.

**Comment by vitorgalvao** [comment]
> If there's a better way to include these, I'm definitely open to the suggestion.

You add them to the Workflow’s directory then reference them via their relative path. They should ship alongside the other files in the Workflow.

**Comment by stephancasas** [comment]
Very cool. I'll adjust this and also refactor to include my updated cache and R/W methods.

Thank you for the suggestions.

**Pull request merged**
