### PR TITLE
Add alfred workflow Python3 library

### PR DESCRIPTION
**Pull request by ischaojie**
[Alfred-Workflow](https://github.com/deanishe/alfred-workflow) is the Python version of the alfred library, but since its author has no plans to support Python3 at this time, I've added Python3 support to it: [Ualfred](https://github.com/ischaojie/ualfred).

### CODE REVIEW

**Comment by vitorgalvao** [comment]
With the Alfred Gallery, this repo will be deprecated in the not too distant future.

Workflow libraries are [listed in a forum thread](https://www.alfredforum.com/topic/10227-workflow-libraries-and-helpers/) (do you have an account, so I can tag you?). However, in the README you recommend using `python`, when `python3` is still the unambiguous binary. Does your library work with `/usr/bin/python3`?

**Comment by ischaojie** [comment]
> in the README you recommend using `python`

This is because the default Python environment is Python3, and should be.


> Does your library work with `/usr/bin/python3`

Of course it does, I've developed my own workflow with `ualfred` and it works fine.

All test env:

```
[[tool.hatch.envs.test.matrix]]
python = ["3.7", "3.8", "3.9", "3.10", "3.11"]
```

**Comment by ischaojie** [comment]
I just created an account: https://www.alfredforum.com/profile/53086-chaojie/

**Comment by vitorgalvao** [comment]
> I just created an account: https://www.alfredforum.com/profile/53086-chaojie/

To clarify, it wasn’t *necessary* to create one. But I’ve linked to it now.

> This is because the default Python environment is Python3, and should be.

It should, yes, but it’s not necessarily. The point is both Apple and Homebrew install Python 3 as `python3` *never* `python`. We will (hopefully) reach the point where `python` will be unambiguously version 3, but we’re definitely not there yet. I know for sure several users reinstalled a version of Python 2 as `python` after the Monterey removal in 12.3.

Unrelated, in the repo’s About you still mention Dean’s URL. And there’s a tag for Alfred 4 but not Alfred 5.

image

**Pull request closed without merging**
